---
version: "3"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    network_mode: bridge
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: /
        target: /srv
    restart: unless-stopped
