---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:0.21.356-ls112 #latest
    container_name: jackett
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
    volumes:
      - jackett:/config
      - /home/sauron/Media/Downloads/:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
volumes:
  jackett:
