---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.5.2.3484-ls19 #latest
    container_name: prowlarr
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
volumes:
  prowlarr:
