---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:arm32v7-latest #latest
    container_name: radarr

    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - radarr:/config
      - /home/sauron/Media/Movies/:/movies #optional
      - /home/sauron/Media/Downloads/:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  radarr:
