---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    network_mode: bridge
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - KEYBOARD=de-de-qwertz #optional
      - TITLE=Webtop #optional
    volumes:
      - webtop:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3010:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
volumes:
  webtop:
